/**
 * loading indicator
 * generated by https://loading.io/
 */
export default function Loading() {
    return (
        <div className='loading-container text-center'>
            <div className="loadingio-spinner-spin-6zkghd55y1m"><div className="ldio-f7ewi0yk2m">
                <div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div>
            </div></div>
        </div>
    );
}